name: Assignment_of_GHA

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  building_part:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build project
        run: mvn clean install

      - name: Test project
        run: mvn clean test
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: target/*.jar 

      # - name: Push build artifacts to a new branch
      #   run: |
      #     git config user.name "anupams20"
      #     git config user.email "anupams20@iitk.ac.in"
      #     git checkout -b artefacts-store
      #     git pull origin artefacts-store
      #     git add .
      #     git commit -m "Upload build artifacts"
      #     git push origin artefacts-store

  download_artifact:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: ./artifacts

      - name: Display files
        run: ls -al ./artifacts
