name: Assignment_of_GHA

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  building_part:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build project
        run: mvn clean install -X
        working-directory: ./ 
      - name: Verify build artifacts
        run: ls -la target/


  testing_part:
    runs-on: ubuntu-latest
    needs: building_part
    steps:
      - uses: actions/checkout@v2  # Checkout the code again for this job

      - name: Test project
        run: mvn clean test
        working-directory: ./  # This assumes the pom.xml is in the root of the repository

  artifact_upload:
    runs-on: ubuntu-latest
    needs: testing_part
    steps:
      - uses: actions/checkout@v2
      
      - name: Print current working directory
        run: pwd
        working-directory: ./
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: target/  
          
      - name: Print current working directory
        run: pwd
       

      - name: List entire repository structure
        run: ls -R

      - name: Verify if artifact exists
        run: |
          if [ -f target/hello-0.0.1-SNAPSHOT.jar ]; then
            echo "Artifact exists!"
          else
            echo "Artifact does not exist!"
            exit 1
          fi


      - name: Push build artifacts to a new branch
        run: |
          git config user.name "anupams20"
          git config user.email "anupams20@iitk.ac.in"
          git checkout -b artefacts-store
          git add target/hello-0.0.1-SNAPSHOT.jar
          git commit -m "Upload build artifacts" || echo "No changes to commit"
          git push origin artefacts-store
