name: Assignment_of_GHA

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  building_part:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build project
        run: mvn clean install -X

  testing_part:
    runs-on: ubuntu-latest
    needs: building_part
    working-directory: ./pom.xml
    steps:
      - name: Test project
        run: mvn clean test

  artifact_upload:
    runs-on: ubuntu-latest
    needs: testing_part
    steps:
      - uses: actions/checkout@v2

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: target/

      - name: Push build artifacts to a new branch
        run: |
          git config user.name "anupams20"
          git config user.email "anupams20@iitk.ac.in"
          git checkout -b artefacts-store
          git add .
          git commit -m "Upload build artifacts"
          git push origin artefacts-store
